# asfd
name: "Github actions"
on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
  pull_request_review:
    types: [submitted]
  workflow_dispatch:
jobs:
  testing_job:
    name: Dump GitHub context
    runs-on: "ubuntu-latest"
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
      - run: echo "$GITHUB_CONTEXT"
      - run: echo "${{ toJson(github.event.pull_request) }}"
      - run: echo "${{ toJson(github.event.pull_request_review) }}"
